- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Create SSL directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/etc/nginx/ssl"
    - "{{ ssl_certs.dest_dir }}"
  become: yes

- name: Deploy SSL certificates
  copy:
    src: "{{ ssl_certs.src_dir }}/{{ item }}"
    dest: "{{ ssl_certs.dest_dir }}/{{ item }}"
    mode: '0644'
  loop:
    - "cloud.pem"
    - "cloud-key.pem"
  become: yes

- name: Deploy Nginx site configs
  template:
    src: "site.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.server_name }}.conf"
  loop: "{{ nginx_sites }}"
  notify: Reload Nginx
  become: yes

- name: Enable sites
  file:
    src: "/etc/nginx/sites-available/{{ item.server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.server_name }}.conf"
    state: link
  loop: "{{ nginx_sites }}"
  notify: Reload Nginx
  become: yes

- name: Remove default site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  become: yes
  notify: Reload Nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes