- name: Install NTP
  ansible.builtin.apt:
    name: ntp
    state: present
    update_cache: no
  become: yes

- name: Ensure NTP service is enabled and running
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: yes
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - borgbackup
      - borgmatic
      - python3-llfuse
    state: present
  become: yes

- name: Create borgmatic configuration directory
  ansible.builtin.file:
    path: /etc/borgmatic
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Add titan-vm root public key to ubuntu's authorized_keys
  authorized_key:
    user: ubuntu
    key: "{{ hostvars['titan-vm']['titan_vm_root_public_key']['content'] | b64decode }}"
  become: yes

- name: Create backup repo directory
  file:
    path: "{{ borg_repo_path }}"
    state: directory
    owner: "{{ borg_repo_owner }}"
    group: "{{ borg_repo_owner }}"
    mode: '0755'
  become: true

- name: Ensure borgmatic env directory exists
  ansible.builtin.file:
    path: /etc/borgmatic/env.d
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Copy env variable for borgmatic
  ansible.builtin.copy:
    src: files/.env
    dest: /etc/borgmatic/env.d/.env
  become: true
