version: 2
logging:
  type: syslog
  level: LOG_INFO
components:
  - libfuse
  - attr_cache
  - azstorage
azstorage:
  type: block
  account_name: bckups
  endpoint: "https://bckups.blob.core.windows.net/"
  account_url: "sp=racwdl&st=2025-04-10T05:57:09Z&se=2025-05-05T13:57:09Z&spr=https&sv=2024-11-04&sr=c&sig=PezLsGuITw4RYCvW1qxfKmKTCKVD%2BgIwMbKn5TL%2BGCA%3D" 
  container: backups           
mount:
  path: "{{ mount_point }}"