- name: NSG for running containers
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ nsg }}"
    rules:
      - name: SSH
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 300
        source_port_range: '*'
        destination_port_range: "{{ ssh_port }}"
        source_address_prefix: "{{ allowed_ip_range }}"
        destination_address_prefix: '*'

      - name: Custom Port SSH
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 1100
        source_port_range: '*'
        destination_port_range: "{{ custom_port }}"
        source_address_prefix: "{{ allowed_ip_range }}"
        destination_address_prefix: '*'

      - name: Allow HTTPS Inbound
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 1110
        source_port_range: '*'
        destination_port_range: '443'
        source_address_prefix: "{{ allowed_ip_range }}"
        destination_address_prefix: '*'

      - name: ICMP
        protocol: ICMP
        direction: Inbound
        access: Allow
        priority: 1120
        source_port_range: '*'
        destination_port_range: '*'
        source_address_prefix: "{{ allowed_ip_range }}"
        destination_address_prefix: '*'

  become: yes
