- name: NSG for running containers
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ nsg }}"
    rules:
      - name: AllowApp8080
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 1000
        source_port_range: '*'
        destination_port_range: '8080'
        source_address_prefix: '*'
        destination_address_prefix: '*'
      - name: AllowApp5000
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 1010
        source_port_range: '*'
        destination_port_range: '5000'
        source_address_prefix: '*'
        destination_address_prefix: '*'
      - name: AllowApp3000
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 1020
        source_port_range: '*'
        destination_port_range: '3000'
        source_address_prefix: '*'
        destination_address_prefix: '*'
      - name: AllowApp4000
        protocol: Tcp
        direction: Inbound
        access: Allow
        priority: 1030
        source_port_range: '*'
        destination_port_range: '4000'
        source_address_prefix: '*'
        destination_address_prefix: '*'
  become: yes
