- name: Install cron
  ansible.builtin.apt:
    update_cache: yes
    name:
      - cron
    state: present
  become: yes


- name: Ensure cron service is started and enabled
  ansible.builtin.systemd:
    name: cron
    enabled: yes
    state: started
  become: yes