- name: install packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - build-essential
      - bat            
      - fd-find
      - fzf
      - git
      - htop
      - iotop
      - lm-sensors
      - plocate
      - ripgrep
      - smartmontools
      - sudo
      - zsh
    state: present
  become: yes
- name: ensure plocate updatedb timer is started and enabled
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    enabled: yes
    state: started
  become: yes