- name: sshd_configuration
  ansible.builtin.copy: 
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '644'
  notify: reload ssh daemon
  become: true