server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: "{{ loki_host_url }}/loki/api/v1/push"
scrape_configs:
  - job_name: systemd-journal
    journal:
      path: /var/log/journal
      labels:
        job: systemd-journal
        app: borgmatic
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: 'borgmatic\.service'
        target_label: 'unit'