services:
  botify:
    build: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - botify-network
    restart: always
      
    environment:
      - GROQ_API_KEY
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
networks:
  botify-network:

volumes:
  botify-data:

