- name: Create a services' directory
  file:
    path: /home/kwabs/services
    state: directory
    mode: '755'
  become: yes

- name: Sync botify folder to remote
  synchronize:
    src: ./files/botify/
    dest: /home/kwabs/services/botify/
    recursive: yes
  become: yes

- name: start botify
  shell: |
    cd /home/kwabs/services/botify && docker compose down && docker compose up --build -d
  become: yes
