loki_version: "2.9.2"
loki_download_url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip"
loki_install_dir: "/usr/local/bin"
loki_config_path: "/etc/loki/loki-config.yaml"