---
- name: Create Prometheus system group
  ansible.builtin.group:
    name: prometheus
    system: yes
    state: present
  become: yes

- name: Create Prometheus system user
  ansible.builtin.user:
    name: prometheus
    group: prometheus
    system: yes
    shell: /sbin/nologin
    createhome: no
  become: yes

- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /etc/prometheus/rules
    - /etc/prometheus/file_sd
    - /var/lib/prometheus
  become: yes

- name: Check if Prometheus is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/prometheus
  register: prometheus_binary

- name: Download and extract Prometheus
  when: not prometheus_binary.stat.exists
  block:
    - name: Download Prometheus
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
      become: yes

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp
        remote_src: yes
      become: yes

    - name: Copy Prometheus binaries
      ansible.builtin.copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        remote_src: yes
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - prometheus
        - promtool
      become: yes

    - name: Copy Prometheus console libraries and templates
      ansible.builtin.copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
        dest: "/etc/prometheus/{{ item }}/"
        remote_src: yes
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - console_libraries
        - consoles
      become: yes

- name: Create Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: yes

- name: Add alert rules
  ansible.builtin.copy:
    src: files/alert_rules.yml
    dest: /etc/prometheus/rules/alert_rules.yml
    owner: prometheus
    group: prometheus
    mode: '644'
  become: yes
  notify: restart prometheus

- name: Create Prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart prometheus


- name: Enable and start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes