- name: reload systemd and enable blobfuse2
  ansible.builtin.systemd:
    name: blobfuse2
    enabled: yes
    daemon_reload: yes
    state: restarted
  listen: "restart blobfuse2"
  
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  listen: "reload systemd"