    alertmanager_version: "0.26.0"
    alertmanager_download_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    alertmanager_install_dir: "/usr/local/bin"
    alertmanager_config_dir: "/etc/alertmanager"
    alertmanager_config_path: "/etc/alertmanager/alertmanager.yml"