- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker's official APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    filename: docker
  become: yes

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  notify: restart docker
  become: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: kwabs
    groups: docker
    append: yes
  become: yes

- name: Reset SSH connection to allow user changes to affect the current session
  ansible.builtin.meta: reset_connection


- name: Create /etc/docker directory
  become: yes
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '755'


- name: Create /etc/docker/daemon.json
  become: yes
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '644'
  notify: restart docker


- name: Ensure Docker is started and enabled at boot
  become: yes
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started


- name: Install Python Docker SDK
  become: yes 
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: yes
  


