- name: Install dependencies
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
    state: present
    update_cache: yes
  become: yes

- name: Add Grafana GPG key
  shell: curl https://packages.grafana.com/gpg.key | apt-key add -
  become: yes

- name: Add Grafana APT repository
  ansible.builtin.command:
    cmd: add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
  become: yes

- name: Configure Grafana to use port 8000
  ansible.builtin.lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;http_port = 3000'
    line: 'http_port = 8000'
    state: present
  become: yes
  notify: Restart Grafana

- name: Start Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

