# - name: Add Grafana APT key
#   apt_key:
#     url: https://apt.grafana.com/gpg.key
#     state: present

# - name: Add Grafana APT repository
#   apt_repository:
#     repo: "deb https://apt.grafana.com stable main"
#     state: present
#     filename: grafana

# - name: Install Grafana Agent
#   apt:
#     name: grafana-agent
#     state: latest
#     update_cache: yes
# - name: Upload Grafana Agent config
#   copy:
#     dest: /etc/grafana-agent.yaml
#     content: |
#       server:
#         log_level: info
#       metrics:
#         wal_directory: /tmp/grafana-agent-wal
#         global:
#           scrape_interval: 15s
#         configs:
#           - name: default
#             scrape_configs:
#               - job_name: integrations/node_exporter_direct_scrape
#                 static_configs:
#                   - targets: ["localhost"]
#             remote_write:
#               - url: "{{ loki_url }}"
#                 basic_auth:
#                   username: "{{ logs_username }}"
#                   password: "{{ grafana_cloud_api_key }}"

# - name: Enable and start Grafana Agent
#   systemd:
#     name: grafana-agent
#     enabled: yes
#     state: restarted
- include_tasks: loki.yml