# - name: Install NTP
#   ansible.builtin.apt:
#     name: ntp
#     state: present
#     update_cache: no
#   become: yes

# - name: Ensure NTP service is enabled and running
#   ansible.builtin.service:
#     name: ntp
#     state: started
#     enabled: yes
#   become: yes

# - name: Update apt cache
#   ansible.builtin.apt:
#     update_cache: yes
#   become: yes

# - name: install packages
#   ansible.builtin.apt:
#     name:
#       - borgbackup
#       - borgmatic
#       - python3-llfuse
#     state: present
#   become: yes

# - name: borgmatic directory
#   ansible.builtin.file:
#     path: /etc/borgmatic
#     state: directory
#     owner: root
#     group: root
#     mode: '0700'
#   become: yes

# - name: config.yaml
#   ansible.builtin.copy:
#     src: files/config.yaml
#     dest: /etc/borgmatic/config.yaml
#     owner: root
#     group: root
#     mode: '600'
#   become: yes

# - name: before.sh
#   ansible.builtin.copy:
#     src: files/before.sh
#     dest: /etc/borgmatic/before.sh
#     owner: root
#     group: root
#     mode: '700'
#   become: yes

# - name: after.sh
#   ansible.builtin.copy:
#     src: files/after.sh
#     dest: /etc/borgmatic/after.sh
#     owner: root
#     group: root
#     mode: '700'
#   become: yes

# - name: error.sh
#   ansible.builtin.copy:
#     src: files/error.sh
#     dest: /etc/borgmatic/error.sh
#     owner: root
#     group: root
#     mode: '700'
#   become: yes

# - name: .env
#   ansible.builtin.copy:
#     src: files/.env
#     dest: /etc/borgmatic/.env
#     owner: root
#     group: root
#     mode: '600'
#   become: yes


# - name: add borgmatic backup to crontab
#   ansible.builtin.cron:
#     name: borgmatic backup
#     minute: "01"
#     hour: "5"
#     user: root
#     job: "/usr/bin/borgmatic --syslog-verbosity 1 > /dev/null 2>&1"
#   become: yes

- name: Generate SSH key if it doesn't exist
  command: ssh-keygen -t ed25519 -f /home/kwabs/.ssh/id_ed25519 -N ""
  args:
    creates: /home/kwabs/.ssh/id_ed25519
  become: true
  become_user: kwabs


- name: read public key from titan-vm
  slurp:
    src: /home/kwabs/.ssh/id_ed25519.pub
  register: titan_vm_public_key
  become: true