- name: Install NTP
  ansible.builtin.apt:
    name: ntp
    state: present
    update_cache: no
  become: yes

- name: Ensure NTP service is enabled and running
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: yes
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install backup-related packages
  ansible.builtin.apt:
    name:
      - borgbackup
      - borgmatic
      - python3-llfuse
    state: present
  become: yes

- name: Create borgmatic configuration directory
  ansible.builtin.file:
    path: /etc/borgmatic
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Copy borgmatic config
  ansible.builtin.copy:
    src: files/config.yaml
    dest: /etc/borgmatic/config.yaml
    owner: root
    group: root
    mode: '0600'
  become: yes

- name: Copy before.sh
  ansible.builtin.copy:
    src: files/before.sh
    dest: /etc/borgmatic/before.sh
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Copy after.sh
  ansible.builtin.copy:
    src: files/after.sh
    dest: /etc/borgmatic/after.sh
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Copy error.sh
  ansible.builtin.copy:
    src: files/error.sh
    dest: /etc/borgmatic/error.sh
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Create BORG_PASSPHRASE environment file
  ansible.builtin.copy:
    dest: /etc/borgmatic/env
    content: |
      BORG_PASSPHRASE={{ borg_passphrase }}
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Create systemd override directory for borgmatic
  ansible.builtin.file:
    path: /etc/systemd/system/borgmatic.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Add environment config to borgmatic systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/borgmatic.service.d/env.conf
    content: |
      [Service]
      EnvironmentFile=/etc/borgmatic/env
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reload systemd and restart borgmatic
  ansible.builtin.systemd:
    daemon_reload: true
    name: borgmatic
    state: restarted
  become: true

- name: Add borgmatic backup to crontab
  ansible.builtin.cron:
    name: borgmatic backup
    minute: "01"
    hour: "5"
    user: root
    job: "/usr/bin/borgmatic --syslog-verbosity 1 > /dev/null 2>&1"
  become: yes

- name: Generate SSH key for root if it doesn't exist
  ansible.builtin.command:
    cmd: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ""
    creates: /root/.ssh/id_ed25519
  become: true

- name: Read root public key from titan-vm
  ansible.builtin.slurp:
    src: /root/.ssh/id_ed25519.pub
  register: titan_vm_root_public_key
  become: true

- name: Initialize remote borg repository from root on kwabs VM
  ansible.builtin.shell: |
    export BORG_PASSPHRASE='{{ borg_passphrase }}'
    borg init --encryption=repokey ssh://ubuntu@test/var/backup/repos/titan-vm
  args:
    creates: /root/.cache/borg/ssh__ubuntu@test_var_backup_repos_titan-vm/config
  become: true
