- name: Install NTP
  ansible.builtin.apt:
    name: ntp
    state: present
    update_cache: no
  become: yes

- name: Ensure NTP service is enabled and running
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: yes
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: install packages
  ansible.builtin.apt:
    name:
      - borgbackup
      - borgmatic
      - python3-llfuse
    state: present
  become: yes

- name: borgmatic directory
  ansible.builtin.file:
    path: /etc/borgmatic
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Copy root-level config.yaml
  ansible.builtin.copy:
    src: files/config.yaml
    dest: /etc/borgmatic/config.yaml
    owner: root
    group: root
    mode: '600'
  become: yes

- name: Create hook directory for root
  ansible.builtin.file:
    path: /etc/borgmatic/hooks
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Copy before.sh hook
  ansible.builtin.copy:
    src: files/before.sh
    dest: /etc/borgmatic/hooks/before.sh
    owner: root
    group: root
    mode: '700'
  become: yes

- name: Copy after.sh hook
  ansible.builtin.copy:
    src: files/after.sh
    dest: /etc/borgmatic/hooks/after.sh
    owner: root
    group: root
    mode: '700'
  become: yes

- name: Copy error.sh hook
  ansible.builtin.copy:
    src: files/error.sh
    dest: /etc/borgmatic/hooks/error.sh
    owner: root
    group: root
    mode: '700'
  become: yes

- name: create .env directory
  ansible.builtin.file:
    path: /etc/borgmatic/env.d
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Copy .env file
  ansible.builtin.copy:
    src: files/.env
    dest: /etc/borgmatic/env.d/.env
    owner: root
    group: root
    mode: '600'
  become: yes

- name: Add borgmatic cron job as root
  ansible.builtin.cron:
    name: borgmatic backup
    minute: "01"
    hour: "5"
    user: root
    job: "/usr/bin/borgmatic --syslog-verbosity 1 > /dev/null 2>&1"
  become: yes

- name: Generate SSH key for root if it doesn't exist
  command: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ""
  args:
    creates: /root/.ssh/id_ed25519
  become: true

- name: Read root public key from titan-vm
  slurp:
    src: /root/.ssh/id_ed25519.pub
  register: titan_vm_root_public_key
  become: true

- name: Initialize remote borg repository from root on kwabs VM
  ansible.builtin.shell: |
    export BORG_PASSPHRASE='{{ borg_passphrase }}'
    borg init --encryption=repokey ssh://ubuntu@test/var/backup/repos/titan-vm
  args:
    creates: /root/.cache/borg/ssh__ubuntu@test_var_backup_repos_titan-vm/config
  become: true
