- name: Start Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

- name: Restart Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
  become: yes

